Fix various type errors
LessWrong2/Lesswrong2 pull request #3494
Opened 2020-09-09 20:56 UTC by Raemon

After making Typescript more strict, a few new bugs came out. Here are some fixes for them.

2020-09-09 22:16 UTC, Discordius requested changes

2020-09-09 22:16 UTC, Discordius commented on packages/lesswrong/components/posts/PostsPage/PostsPage.tsx
> +    if (post.shortform) return `A collection of shorter posts ${post.user && `by ${forumTitleSetting.get()} user ${post.user.displayName}`}`
Won't this print ` a collection of shorter posts undefined` when there is no user?

2020-09-09 22:19 UTC, Raemon commented
Whoops. Hopefully fixed those two issues.

2020-09-10 00:55 UTC, Discordius approved these changes

2020-09-10 00:55 UTC, merged