Add ability to set image for social media preview
LessWrong2/Lesswrong2 pull request #3605
Opened 2020-10-28 17:41 UTC by jpaddison3

An oft-requested feature is for the ability to select the image available for sharing on social media. The perfect version would let you choose from the images in your post. .. I went with an easy version. 

Add a field to the Posts schema that stores the cloudinary ID of a user-uploaded image for the social media preview.

Most of the work was fixing the styling of `ImageUpload`.

2020-10-28 18:52 UTC, Discordius commented
Hmm, we've designed the post-editor so that for a new user, who doesn't have moderation power, they there are no advanced menus they have to navigate and think about. I think this is pretty important. 

The way I would have handled the social media images with minimal effort was to just scan the post for the first linked image, and then set that as the social media image. 

I am not sure how to go ahead with this. I am not a huge fan of showing every new user that kind of cluttery "Options" menu, but do think setting social images is pretty valuable. 

On a more object-level, I also can't get it to work locally. Nothing seems to happen when I click on the button. Maybe some chance I don't have a setting set in localhost that is required to make it work?

2020-10-28 22:30 UTC, jpaddison3 commented
Ah, yeah, you need to configure an upload preset (sp?) like banner and grid images have. See the new database setting.

Anyway, happy to talk more tomorrow.

2020-10-29 18:16 UTC, jpaddison3 commented
Did you get it working?

2020-10-29 18:22 UTC, jpaddison3 commented
> I am not sure how to go ahead with this. I am not a huge fan of showing every new user that kind of cluttery "Options" menu, but do think setting social images is pretty valuable.

I thought we were going that direction with the coauthors option (once we got it working). But nevertheless I agree it's quite minimal now and would be happy to use the first image. I initially looked at it and was like, erg, the only thing you have when rendering the post is the html-rendered contents. I guess you could have a callback on post-submission that sets the a field on the post object? I'd be curious for your take on how easy that is.

2020-10-29 19:56 UTC, Discordius commented
(Have more thoughts but have to head into more meetings)

2020-10-31 18:22 UTC, Discordius commented
Ok, now actually reviewing the code. I am pretty sure this breaks the preview image for all posts that were submitted before this functionality was added? I.e. it removes the default preview image. Does that seem right to me, and did you test that?

2020-11-03 13:47 UTC, jpaddison3 commented
Correct, and I'm sorry I didn't check that.

2020-11-06 16:05 UTC, jpaddison3 commented
This now auto-sets the social preview image as the first image in the post. Admins and mods can still manually set the image using the upload widget.

2020-11-06 16:05 UTC, jpaddison3 commented
@Discordius PTAL

2020-11-06 23:35 UTC, Discordius commented
cool, will test it and play around with it today. Thank you!

2020-11-07 02:25 UTC, Discordius commented
This... still breaks the preview images for all historical posts?

2020-11-07 02:45 UTC, Discordius requested changes

2020-11-07 02:45 UTC, Discordius commented on packages/lesswrong/lib/collections/posts/helpers.ts
> +  if (manualId) return `https://res.cloudinary.com/cea/image/upload/c_fill,ar_1.91,g_auto/${manualId}`
This will presumably break for us? Given the `cea` domain. Would be great to factor this out into a setting.

2020-11-07 02:46 UTC, Discordius commented
Fixed it in this PR: https://github.com/LessWrong2/Lesswrong2/pull/3647

2020-11-07 02:46 UTC, Discordius commented
Waiting on you to comment on that one, then we can merge that one, and close this one

2020-11-07 10:52 UTC, jpaddison3 commented
Sorry about the default-cea cloudname.

2020-11-07 10:54 UTC, jpaddison3 commented
The lack of setting the default social preview was intentional. It is handled the same way it always has been. I decided that it would be better for us not to bother setting the default, as then a consumer of the API who didn't want to use the default would have a hard time telling if we were intentionally setting it or just using a default value.

2020-11-07 18:37 UTC, Discordius commented
Yeah, I don't feel super strongly about whether we should set the default, and the change wasn't intended as a thing that your PR missed, just something that seemed marginally better to me, as the logic around this becomes a bit more complicated.

2020-11-09 10:36 UTC, jpaddison3 commented
I misunderstood by virtue of looking at this too late at night. I read the "this breaks old preview images" and your "set default image" as being connected and wildly assumed that it was setting a default value [here](https://github.com/LessWrong2/Lesswrong2/pull/3605/files#diff-2e166dbca57458db3449bf2171d76c817b6f14cac6c1dcce3e579818a9ece42dR188) (A careful reading of your concern, would reveal that changing that line would not actually help, so yeah, probably should stop with the late night githubing)

2020-11-10 01:49 UTC, merged