Add number of wiki edits to user profiles
LessWrong2/Lesswrong2 pull request #4074
Opened 2021-06-02 11:59 UTC by jpaddison3

To give feedback to users who make wiki edits, we wanted to showcase their contributions on their profile. @s-cheng joined us on this one.

This PR was _almost_ dead simple. It looked like she had it after figuring out that tagRevisionCount could be a denormalizedCountOfReferences. However, the way denormalizedCountOfReferences works is that it registers callbacks on the foreign collection to increment the count. Unfortunately, Revisions are created without going through the normal mutator flow that would involve running those callbacks. Instead the new revisions are directly inserted inside of make_editable_callbacks.

Which brings us to our proposed refactor: the make_editable_callbacks can very easily be refactored to call createMutator instead of Connectors.create. I've examined createMutator, and the only effects it has are to run callbacks, which is what we want. Using createMutator allows denormalizedCountOfReferences to work as normal, and would allow us to remove the special-cased afterCreateRevisionCallback's.

Here's what the UI looks like:
![image](https://user-images.githubusercontent.com/10352319/120476250-372df400-c35f-11eb-95d4-18f95ddabe98.png)

2021-06-04 19:44 UTC, Discordius requested changes
This does require a migration that fills in the default values, but other than that seems good.

2021-06-04 19:44 UTC, Discordius commented on packages/lesswrong/lib/collections/users/custom_fields.ts
> +    ...schemaDefaultValue(0)
The `denormalizedCountOfReferences` function already comes with the `schemaDefaultValue`, so you can ommit this

2021-06-07 12:55 UTC, jpaddison3 commented
Waiting on this to submit the next in the chain. You can view the next diff [here](https://github.com/centre-for-effective-altruism/EAForum/compare/sarah-wiki-edits...wiki-showcase), iff you're interested.

2021-06-07 12:59 UTC, Discordius approved these changes

2021-06-07 12:59 UTC, merged