Fix bugs in user handling
LessWrong2/Lesswrong2 pull request #4085
Opened 2021-06-15 02:01 UTC by jimrandomh

Fixes the password field on the login form being mislabeled. Fixes the terrible internal-error message you get when you attempt to sign up with a username or email that's already taken. Fixes crash when a Sunshine who isn't an Admin attempts to edit a user. Fix incorrect permissions on the Legacy field, which leaked all imported password hashes.

2021-06-15 03:45 UTC, Discordius approved these changes

2021-06-15 03:46 UTC, Discordius commented
Wait, are we confident that nothing else will break with the legacy field being no longer exposed? Closing it quickly seems more important, but can imagine something like the legacy URL redirects breaking.

2021-06-15 03:50 UTC, Discordius requested changes
The `legacy` boolean field should definitely be public

2021-06-15 06:31 UTC, jimrandomh commented
I'm confident nothing will break - the field isn't used in any fragments, so it isn't ever going to be permission-gated anywhere it's actually used. But also it's just the boolean and has no security implications, I was thinking of `legacyData` which isn't in the schema at all (though it is in the database).

2021-06-16 18:18 UTC, Discordius approved these changes

2021-06-16 18:18 UTC, Discordius commented
Cool, if it isn't in any fragments, shouldn't cause any problems.

2021-06-17 07:01 UTC, merged